config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get 'past-calculator', to: 'calculator#pastcalculator'
  get 'past-results', to: 'calculator#pastresults'

  get 'future-calculator', to: 'calculator#futurecalculator'
  get 'future-results', to: 'calculator#futureresults'

  get 'yield-calculator', to: 'calculator#yieldcalculator'
  get 'yield-results', to: 'calculator#yieldresults'

  # get 'suburb-stats', to: 'stats#suburbstats'
  # get 'suburb-results', to: 'stats#suburbresults'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController

  def pastcalculator
  end

  def pastresults
    @year = params[:yearSold].to_i
    @current_price = params[:currentSalePrice].to_i
    @past_price = params[:lastSalePrice].to_i
    @difference = @current_price - @past_price
    @growth_total = (@difference.to_f / @past_price) * 100
    @years_difference = Time.new.year - @year
    @average_annual_growth_percentage = (@growth_total / @years_difference).round(2)
  end

  def futurecalculator
  end

  def futureresults
    @property_value = params[:propertyValue].to_i
    @growth_rate = params[:growthRate].to_i
    @years_display = params[:yearsDisplay].to_i
    @growth_percentage = @growth_rate.to_f / 100
    @growth_amount = @property_value * @growth_percentage
    @growth_int = @growth_percentage + 1
    @current_year = Time.new.year
    @count = 0
  end

  def yieldcalculator
  end

  def yieldresults
    @weekly_rent = params[:weeklyRent].to_i
    @monthly_rent = params[:monthlyRent].to_i
    @property_price = params[:propertyPrice].to_i
    @annual_rent = (@weekly_rent / 7) * 365
    @y = @annual_rent / @property_price.to_f * 100
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  require 'open-uri'
  require 'nokogiri'

  def suburbresults
    @state = params[:state]
    @suburb = params[:suburb]
    @postode = params[:postcode]

    doc = Nokogiri::HTML(open("https://flatmates.com.au/value-my-room/#{@suburb}-#{@postcode}"))
    @headline = doc.css('body')
  end


  def suburbstats
  end


end


# body > div.cdiv > section.b_0cz > div > div > div > div > div > div.b-suburbprofilepage > div.b-suburbprofilepage__stat > div > table > tbody > tr:nth-child(1) > td:nth-child(3)

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/calculator/futurecalculator.html.erb
<div class="future-growth">
  <div class="content">
    <div class="row justify-content-center">
      <div class="col-12">
      <h1>Estimate A Property's Future Growth Value</h1>
    <br>
      <p style="font-size: 1.4em;"><strong>Use this calculator to display the future value of a property based off a hypothetical growth percentage</strong></p>
        <form action="/future-results">
          <div class="form-group">
            <label for="propertyValue"><strong>Value of Property </strong></label>
            <input type="number" class="form-control" name="propertyValue" aria-describedby="propertyValue" placeholder="$">
          </div>
          <div class="form-group">
            <label for="growthRate"><strong>Annual Growth Rate</strong></label>
            <input type="number" step=".1" class="form-control" name="growthRate" placeholder="%">
          </div>
          <div class="form-group">
            <label for="displayYears"><strong>Years to Display</strong></label>
            <input type="number" class="form-control" name="yearsDisplay" aria-describedby="yearsDisplay" placeholder="Years">
            <small id="propertyHelp" class="form-text text-muted">How many years of results would you like to see displayed?</small>
          </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary btn-lg">Calculate</button>
            </div>

        </form>
      </div>
    </div>
  </div>
</div>

app/views/calculator/futureresults.html.erb
<div class="future-results">
  <div class="content">
    <div class="row justify-content-center">
      <div class="col-12">
      <h1>Future Value at <%= @growth_rate %>% Annual Growth</h1>
      <br>
      <% until @count == @years_display %>
      <ul>
      <li style="font-size: 1.4em;"><%= "#{@current_year} = $#{@property_value.round(0).to_s(:delimited)}" %></li>
      </ul>
      <% @count += 1 %>
      <% @current_year += 1 %>
      <% @property_value *= @growth_int %>
      <% end %>
      <p style="font-size: 1.2em;"><%= link_to "Run Another Calculation", future_calculator_path %></p>
      <p style="margin-top: -30px; font-size: 1.2em;"><%= link_to "Return to Home Page", root_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/calculator/pastcalculator.html.erb
<div class="past-growth">
  <div class="content">
    <div class="row justify-content-center">
      <div class="col-12">
        <h1>Calculate A Property's Past Growth Rate</h1>
        <p style="font-size: 1.4em;"> <strong>Use this calculator to find out the past growth performance of a property.</strong></p>
        <form action="/past-results">
          <div class="form-group">
            <label for="yearSold"><strong>Year of Last Sale</strong></label>
            <input type="number" class="form-control" name="yearSold" aria-describedby="yearSold" placeholder="e.g 2004">
          </div>
          <div class="form-group">
            <label for="lastSalePrice"><strong>Previous Sale Price</strong></label>
            <input type="number" class="form-control" name="lastSalePrice" placeholder="$">
          </div>
          <div class="form-group">
            <label for="currentSalePrice"><strong>Current Sale Price</strong></label>
            <input type="number" class="form-control" name="currentSalePrice" placeholder="$">
          </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary btn-lg">Calculate</button>
            </div>
        </form>
        <p><a href="https://www.domain.com.au/property-profile">Domain's Home Price Guide</a> is a handy way to access previous prices of the property in question. Just enter the address and it will provide all of that property's available sales history
        </p>
      </div>
    </div>
  </div>
</div>

app/views/calculator/pastresults.html.erb
<div class="past-results">
  <div class="content">
    <div class="row justify-content-center">
      <div class="col-12">
      <h1>Past Growth Rate</h1>
      <br>
      <h1><strong><%=@average_annual_growth_percentage %>% per annum</strong></h1>
      <br>
      <p style="font-size: 1.2em;"><%= link_to "Run Another Calculation", past_calculator_path %></p>
      <p style="margin-top: -30px; font-size: 1.2em;"><%= link_to "Return to Home Page", root_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/calculator/yieldcalculator.html.erb
<div class="yield-first">
  <div class="content">
    <div class="row justify-content-center">
      <div class="col-12">
      <h1 style="padding-bottom: 6px;">Calculate a Property's Rental Yield</h1>
      <p style="font-size: 1.3em;"><strong>Use this calculator to determine the rental yield of property.</strong></p>
        <form action="/yield-results">
          <div class="form-group" style="padding: 0 14px;">
            <label for="weeklyRent"><strong>Weekly Rent</strong></label>
            <input type="number" class="form-control" name="weeklyRent" aria-describedby="weeklyRent" placeholder="$">
          </div>
          <div class="form-group" style="padding: 0 14px;">
            <label for="propertyPrice"><strong>Property Price</strong></label>
            <input type="number" class="form-control" name="propertyPrice" aria-describedby="propertyPrice" placeholder="$">
            <small id="propertyHelp" class="form-text text-muted">Enter the current value of the property</small>
          </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary btn-lg">Calculate</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/calculator/yieldresults.html.erb
<div class="yield-results">
  <div class="content">
    <div class="row justify-content-center">
      <div class="col-12">
      <h1>Rental Yield</h1>
      <h1><strong><%=@y.round(2) %>% </strong></h1> <br>
      <p><%= link_to "Run Another Calculation", yield_calculator_path %></p>
      <p style="margin-top: -30px;"><%= link_to "Return to Home Page", root_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPropertyCalculatorPastGrowth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-page">
  <div class="content">
    <div class="row justify-content-center">
      <div class="col-12">
        <h1>Welcome</h1>
        <p style="font-size: 1.4em;"><strong>Please make use of these free property investment calculators</strong></p>
        <ul>
          <li><%= link_to "Rental Yield Calculator", yield_calculator_path %></li>
          <br>
          <li><%= link_to "Future Growth Calculator", future_calculator_path %></li>
          <br>
          <li><%= link_to "Past Growth Calculator", past_calculator_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>